let array_01_value=  {
    ulong_msCounter: 54348785,
    ulong_SorterEncoder: 961088068,
    ulong_SorterEncoder2: 961076097,
    ulong_SorterEncoder3: 961088034,
    uint_PLCStatus: 0,
    uint_Data: [ 0, 0, 0, 21845 ],
    uint_EDS_ComData_Control: 1,
    uint_EDS_ComData_TsSSMMHHDD: 2,
    uint_EDS_ComData_TsMM__YYYY: 3,
    uint_EDS_ComData_Mode: 4,
    uint_EDS_ComData_State: 5,
    uint_EDS_ComData_Ins: 6,
    uint_EDS_ComData_Fault: 7,
    uint_EDS_ComData_Diag: 8,
    uint_MHE_Id0Data_Vid_num1_8: 1,
    uint_MHE_Id0Data_Vid_num9_16: 2,
    uint_MHE_Id0Data_EDSPseudoId: 3,
    uint_MHE_Id0Data_PassNumber: 4,
    uint_MHE_Id0Data_TsSSMM: 5,
    uint_MHE_Id0Data_TsHHDD: 6,
    uint_MHE_Id0Data_TsMM_PcsTrk: 7,
    uint_MHE_Id0Data_TsYYYY: 8,
    uint_MHE_Id0Data_SecurityRoutineCode: 9,
    uint_MHE_Id0Data_PieceDispo: 10,
    uint_MHE_Id0Data_PrjSpec: 11,
    uint_MHE_Id0Data_GlobalId: 12,
    uint_MHE_Id1Data_Vid_num1_8: 1,
    uint_MHE_Id1Data_Vid_num9_16: 2,
    uint_MHE_Id1Data_EDSPseudoId: 3,
    uint_MHE_Id1Data_PassNumber: 4,
    uint_MHE_Id1Data_TsSSMM: 5,
    uint_MHE_Id1Data_TsHHDD: 6,
    uint_MHE_Id1Data_TsMM_PcsTrk: 7,
    uint_MHE_Id1Data_TsYYYY: 8,
    uint_MHE_Id1Data_SecurityRoutineCode: 9,
    uint_MHE_Id1Data_PieceDispo: 10,
    uint_MHE_Id1Data_PrjSpec: 11,
    uint_MHE_Id1Data_GlobalId: 12,
    uint_DeviceConnected: [ 1, 2, 3, 4 ]
}
module.exports ={value:array_01_value};