let array_02_value=  {
    uint_CMAlive: 2003,
    uint_Mode: 0,
    uint_State: 0,
    uint_Spare1: 0,
    uint_OutputState: [ 34, 0, 0, 0 ],
    uint_MotorSpeed: [ 0, 0, 0, 0, 0, 0 ],
    uint_CMStatus: 0,
    uint_MHE_ComData_Control: 1,
    uint_MHE_ComData_Mode: 2,
    uint_MHE_ComData_Fault: 3,
    uint_MHE_ComData_Clear: 4,
    uint_MHE_IdData_Align: 1,
    uint_MHE_IdData_PassNumber: 2,
    uint_MHE_IdData_Vid_num1_8: 3,
    uint_MHE_IdData_Vid_num9_16: 4,
    byte_MHE_IdData_PieceBcr: [1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0],
    uint_MHE_IdData_GlobalId: 1,
    uint_MHE_IdData_PrjSpec: 2,
    uint_MHE_IdData_SecurityRoutineCode: 3,
    uint_MHE_IdData_DynamicScreeningAlgo: 4,
    uint_MHE_IdData_TsSSMMHHDD: 5,
    uint_MHE_IdData_TsMM__YYYY: 6
}
module.exports ={value:array_02_value};